config/routes.rb
Rails.application.routes.draw do
  resources :bg_kazeis

  resources :bg_kihon_histories

  resources :bg_kihons

  resources :bank_accounts

  resources :contacts

  resources :addressees

  resources :memos

  root to: 'home#index'
  resources :person_histories

  resources :people do
    resources :person_histories
    resources :memos
    resources :addressees
    resources :contacts
    resources :bank_accounts
  end

end

app/models/person.rb
class Person < ActiveRecord::Base
  has_many :person_histories, foreign_key: "number", primary_key: "number"
  has_many :memos, foreign_key: "number", primary_key: "number"
  has_many :contacts, foreign_key: "number", primary_key: "number"
  has_many :addressees, foreign_key: "number", primary_key: "number"
  has_many :bank_accounts, foreign_key: "number", primary_key: "number"
  belongs_to :bg_kihon, foreign_key: "number", primary_key: "number"

  after_save :create_history #更新時（create,update時に履歴を作成する）

  private
  #履歴の書き出し
  def create_history
    if self.person_histories.exists?
      history_no = {"history_no" => (self.person_histories.last[:history_no].to_i + 1).to_s}
    else
      history_no = {"history_no" => "1"}
    end
    data_attributes = self.attributes
    #自動更新項目を除外
    data_attributes.except! "id","number","created_at","updated_at"
    #履歴番号を設定
    data_attributes.merge!(history_no)
    new_history = self.person_histories.new(data_attributes)
    new_history.save
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:number, :person_type, :legal_cd, :legal_position_cd, :name, :name_k, :branch_name, :branch_name_k, :zipno, :address1_cd, :address2_cd, :address3_cd, :address4_cd, :address5_cd, :address, :address_kata, :n_zei_id, :serch_name, :serch_name_k, :update_date, :update_reason)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_for @person, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :number, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :number, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :person_type, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :person_type, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :legal_cd, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :legal_cd, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :legal_position_cd, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :legal_position_cd, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :name_k, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name_k, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :branch_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :branch_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :branch_name_k, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :branch_name_k, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :zipno, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :zipno, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :address1_cd, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :address1_cd, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :address2_cd, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :address2_cd, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :address3_cd, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :address3_cd, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :address4_cd, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :address4_cd, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :address5_cd, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :address5_cd, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :address, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :address, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :address_kata, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :address_kata, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :n_zei_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :n_zei_id, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :serch_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :serch_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :serch_name_k, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :serch_name_k, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :update_date, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :update_date, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :update_reason, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :update_reason, :class => 'text_field' %>
    </div>
  </div>

  
  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            people_path, :class => 'btn btn-default' %>
 
<% end %>

app/views/people/_show.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:number) %>:</strong></dt>
  <dd><%= @bg_kihon.person.number %></dd>
  <dt><strong><%= model_class.human_attribute_name(:person_type) %>:</strong></dt>
  <dd><%= @bg_kihon.person.person_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:legal_cd) %>:</strong></dt>
  <dd><%= @bg_kihon.person.legal_cd %></dd>
  <dt><strong><%= model_class.human_attribute_name(:legal_position_cd) %>:</strong></dt>
  <dd><%= @bg_kihon.person.legal_position_cd %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @bg_kihon.person.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name_k) %>:</strong></dt>
  <dd><%= @bg_kihon.person.name_k %></dd>
  <dt><strong><%= model_class.human_attribute_name(:branch_name) %>:</strong></dt>
  <dd><%= @bg_kihon.person.branch_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:branch_name_k) %>:</strong></dt>
  <dd><%= @bg_kihon.person.branch_name_k %></dd>
  <dt><strong><%= model_class.human_attribute_name(:zipno) %>:</strong></dt>
  <dd><%= @bg_kihon.person.zipno %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address1_cd) %>:</strong></dt>
  <dd><%= @bg_kihon.person.address1_cd %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address2_cd) %>:</strong></dt>
  <dd><%= @bg_kihon.person.address2_cd %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address3_cd) %>:</strong></dt>
  <dd><%= @bg_kihon.person.address3_cd %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address4_cd) %>:</strong></dt>
  <dd><%= @bg_kihon.person.address4_cd %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address5_cd) %>:</strong></dt>
  <dd><%= @bg_kihon.person.address5_cd %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @bg_kihon.person.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address_kata) %>:</strong></dt>
  <dd><%= @bg_kihon.person.address_kata %></dd>
  <dt><strong><%= model_class.human_attribute_name(:n_zei_id) %>:</strong></dt>
  <dd><%= @bg_kihon.person.n_zei_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:serch_name) %>:</strong></dt>
  <dd><%= @bg_kihon.person.serch_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:serch_name_k) %>:</strong></dt>
  <dd><%= @bg_kihon.person.serch_name_k %></dd>
  <dt><strong><%= model_class.human_attribute_name(:update_date) %>:</strong></dt>
  <dd><%= @bg_kihon.person.update_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:update_reason) %>:</strong></dt>
  <dd><%= @bg_kihon.person.update_reason %></dd>
</dl>

app/views/people/edit.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/people/index.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:number) %></th>
      <th><%= model_class.human_attribute_name(:person_type) %></th>
      <th><%= model_class.human_attribute_name(:legal_cd) %></th>
      <th><%= model_class.human_attribute_name(:legal_position_cd) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:name_k) %></th>
      <th><%= model_class.human_attribute_name(:branch_name) %></th>
      <th><%= model_class.human_attribute_name(:branch_name_k) %></th>
      <th><%= model_class.human_attribute_name(:zipno) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:address_kata) %></th>
      <th><%= model_class.human_attribute_name(:n_zei_id) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= link_to person.id, person_path(person) %></td>
        <td><%= person.number %></td>
        <td><%= person.person_type %></td>
        <td><%= person.legal_cd %></td>
        <td><%= person.legal_position_cd %></td>
        <td><%= person.name %></td>
        <td><%= person.name_k %></td>
        <td><%= person.branch_name %></td>
        <td><%= person.branch_name_k %></td>
        <td><%= person.zipno %></td>
        <td><%= person.address %></td>
        <td><%= person.address_kata %></td>
        <td><%= person.n_zei_id %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_person_path(person), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      person_path(person),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_person_path,
            :class => 'btn btn-primary' %>

app/views/people/new.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/people/show.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:number) %>:</strong></dt>
  <dd><%= @person.number %></dd>
  <dt><strong><%= model_class.human_attribute_name(:person_type) %>:</strong></dt>
  <dd><%= @person.person_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:legal_cd) %>:</strong></dt>
  <dd><%= @person.legal_cd %></dd>
  <dt><strong><%= model_class.human_attribute_name(:legal_position_cd) %>:</strong></dt>
  <dd><%= @person.legal_position_cd %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @person.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name_k) %>:</strong></dt>
  <dd><%= @person.name_k %></dd>
  <dt><strong><%= model_class.human_attribute_name(:branch_name) %>:</strong></dt>
  <dd><%= @person.branch_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:branch_name_k) %>:</strong></dt>
  <dd><%= @person.branch_name_k %></dd>
  <dt><strong><%= model_class.human_attribute_name(:zipno) %>:</strong></dt>
  <dd><%= @person.zipno %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address1_cd) %>:</strong></dt>
  <dd><%= @person.address1_cd %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address2_cd) %>:</strong></dt>
  <dd><%= @person.address2_cd %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address3_cd) %>:</strong></dt>
  <dd><%= @person.address3_cd %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address4_cd) %>:</strong></dt>
  <dd><%= @person.address4_cd %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address5_cd) %>:</strong></dt>
  <dd><%= @person.address5_cd %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @person.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address_kata) %>:</strong></dt>
  <dd><%= @person.address_kata %></dd>
  <dt><strong><%= model_class.human_attribute_name(:n_zei_id) %>:</strong></dt>
  <dd><%= @person.n_zei_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:serch_name) %>:</strong></dt>
  <dd><%= @person.serch_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:serch_name_k) %>:</strong></dt>
  <dd><%= @person.serch_name_k %></dd>
  <dt><strong><%= model_class.human_attribute_name(:update_date) %>:</strong></dt>
  <dd><%= @person.update_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:update_reason) %>:</strong></dt>
  <dd><%= @person.update_reason %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              people_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_person_path(@person), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              person_path(@person),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

<div>
  <%= render :partial => 'person_histories/index' %>
</div>
<div>
  <%= render :partial => 'memos/index', locals: {memos: @person.memos} %>
</div>
<div>
  <%= render :partial => 'addressees/index', locals: {addressees: @person.addressees}  %>
</div>
<div>
  <%= render :partial => 'contacts/index', locals: {contacts: @person.contacts}  %>
</div>
<div>
  <%= render :partial => 'bank_accounts/index', locals: {bank_accounts: @person.bank_accounts}  %>
</div>