config/routes.rb
Rails.application.routes.draw do
  resources :bg_kazeis

  resources :bg_kihon_histories

  resources :bg_kihons

  resources :bank_accounts

  resources :contacts

  resources :addressees

  resources :memos

  root to: 'home#index'
  resources :person_histories

  resources :people do
    resources :person_histories
    resources :memos
    resources :addressees
    resources :contacts
    resources :bank_accounts
  end

end

app/models/bg_kihon.rb
class BgKihon < ActiveRecord::Base
  has_many :bg_kihon_histories, foreign_key: "number", primary_key: "number"
  has_many :bg_kazeis, foreign_key: "number", primary_key: "number"
  has_one :person,  foreign_key: "number", primary_key: "number"

  after_save :create_history #更新時（create,update時に履歴を作成する）

  private
  #履歴の書き出し
  def create_history
    if self.bg_kihon_histories.exists?
      history_no = {"history_no" => (self.bg_kihon_histories.last[:history_no].to_i + 1).to_s}
    else
      history_no = {"history_no" => "1"}
    end
    data_attributes = self.attributes
    #自動更新項目を除外
    data_attributes.except! "id","number","created_at","updated_at"
    #履歴番号を設定
    data_attributes.merge!(history_no)
    new_history = self.bg_kihon_histories.new(data_attributes)
    new_history.save
  end
end

app/controllers/bg_kihons_controller.rb
class BgKihonsController < ApplicationController
  before_action :set_bg_kihon, only: [:show, :edit, :update, :destroy]

  # GET /bg_kihons
  # GET /bg_kihons.json
  def index
    @bg_kihons = BgKihon.all
  end

  # GET /bg_kihons/1
  # GET /bg_kihons/1.json
  def show
  end

  # GET /bg_kihons/new
  def new
    @bg_kihon = BgKihon.new
  end

  # GET /bg_kihons/1/edit
  def edit
  end

  # POST /bg_kihons
  # POST /bg_kihons.json
  def create
    @bg_kihon = BgKihon.new(bg_kihon_params)

    respond_to do |format|
      if @bg_kihon.save
        format.html { redirect_to @bg_kihon, notice: 'Bg kihon was successfully created.' }
        format.json { render :show, status: :created, location: @bg_kihon }
      else
        format.html { render :new }
        format.json { render json: @bg_kihon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bg_kihons/1
  # PATCH/PUT /bg_kihons/1.json
  def update
    respond_to do |format|
      if @bg_kihon.update(bg_kihon_params)
        format.html { redirect_to @bg_kihon, notice: 'Bg kihon was successfully updated.' }
        format.json { render :show, status: :ok, location: @bg_kihon }
      else
        format.html { render :edit }
        format.json { render json: @bg_kihon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bg_kihons/1
  # DELETE /bg_kihons/1.json
  def destroy
    @bg_kihon.destroy
    respond_to do |format|
      format.html { redirect_to bg_kihons_url, notice: 'Bg kihon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bg_kihon
      @bg_kihon = BgKihon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bg_kihon_params
      params.require(:bg_kihon).permit(:number, :kazei_type, :toriatukaitabako_type, :tokureitabako_type, :send_type, :stop_sdate, :stop_edate, :chenge_date, :change_jiyu)
    end
end

app/helpers/bg_kihons_helper.rb
module BgKihonsHelper
end

app/views/bg_kihons/_form.html.erb
<%= form_for @bg_kihon, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :number, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :number, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :kazei_type, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :kazei_type, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :toriatukaitabako_type, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :toriatukaitabako_type, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :tokureitabako_type, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :tokureitabako_type, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :send_type, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :send_type, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :stop_sdate, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :stop_sdate, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :stop_edate, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :stop_edate, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :chenge_date, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :chenge_date, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :change_jiyu, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :change_jiyu, :class => 'text_field' %>
    </div>
  </div>

  
  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            bg_kihons_path, :class => 'btn btn-default' %>
 
<% end %>

app/views/bg_kihons/edit.html.erb
<%- model_class = BgKihon -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bg_kihons/index.html.erb
<%- model_class = BgKihon -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:number) %></th>
      <th><%= model_class.human_attribute_name(:kazei_type) %></th>
      <th><%= model_class.human_attribute_name(:toriatukaitabako_type) %></th>
      <th><%= model_class.human_attribute_name(:tokureitabako_type) %></th>
      <th><%= model_class.human_attribute_name(:send_type) %></th>
      <th><%= model_class.human_attribute_name(:stop_sdate) %></th>
      <th><%= model_class.human_attribute_name(:stop_edate) %></th>
      <th><%= model_class.human_attribute_name(:chenge_date) %></th>
      <th><%= model_class.human_attribute_name(:change_jiyu) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @bg_kihons.each do |bg_kihon| %>
      <tr>
        <td><%= link_to bg_kihon.id, bg_kihon_path(bg_kihon) %></td>
        <td><%= bg_kihon.number %></td>
        <td><%= bg_kihon.kazei_type %></td>
        <td><%= bg_kihon.toriatukaitabako_type %></td>
        <td><%= bg_kihon.tokureitabako_type %></td>
        <td><%= bg_kihon.send_type %></td>
        <td><%= bg_kihon.stop_sdate %></td>
        <td><%= bg_kihon.stop_edate %></td>
        <td><%= bg_kihon.chenge_date %></td>
        <td><%= bg_kihon.change_jiyu %></td>
        <td><%=l bg_kihon.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_bg_kihon_path(bg_kihon), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      bg_kihon_path(bg_kihon),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_bg_kihon_path,
            :class => 'btn btn-primary' %>

app/views/bg_kihons/new.html.erb
<%- model_class = BgKihon -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bg_kihons/show.html.erb
<%- model_class = BgKihon -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:number) %>:</strong></dt>
  <dd><%= @bg_kihon.number %></dd>
  <dt><strong><%= model_class.human_attribute_name(:kazei_type) %>:</strong></dt>
  <dd><%= @bg_kihon.kazei_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:toriatukaitabako_type) %>:</strong></dt>
  <dd><%= @bg_kihon.toriatukaitabako_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tokureitabako_type) %>:</strong></dt>
  <dd><%= @bg_kihon.tokureitabako_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:send_type) %>:</strong></dt>
  <dd><%= @bg_kihon.send_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:stop_sdate) %>:</strong></dt>
  <dd><%= @bg_kihon.stop_sdate %></dd>
  <dt><strong><%= model_class.human_attribute_name(:stop_edate) %>:</strong></dt>
  <dd><%= @bg_kihon.stop_edate %></dd>
  <dt><strong><%= model_class.human_attribute_name(:chenge_date) %>:</strong></dt>
  <dd><%= @bg_kihon.chenge_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:change_jiyu) %>:</strong></dt>
  <dd><%= @bg_kihon.change_jiyu %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              bg_kihons_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_bg_kihon_path(@bg_kihon), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              bg_kihon_path(@bg_kihon),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

<div>
  <%= render :partial => 'bg_kihon_histories/index' %>
</div>
<div>
  <%= render :partial => 'people/show' %>
</div>
<div>
  <%= render :partial => 'bg_kazeis/index' %>
</div>