config/routes.rb
Rails.application.routes.draw do
  resources :bg_kazeis

  resources :bg_kihon_histories

  resources :bg_kihons

  resources :bank_accounts

  resources :contacts

  resources :addressees

  resources :memos

  root to: 'home#index'
  resources :person_histories

  resources :people do
    resources :person_histories
    resources :memos
    resources :addressees
    resources :contacts
    resources :bank_accounts
  end

end

app/models/bank_account.rb
class BankAccount < ActiveRecord::Base
  belongs_to :person, foreign_key: "number", primary_key: "number"
end

app/controllers/bank_accounts_controller.rb
class BankAccountsController < ApplicationController
  before_action :set_bank_account, only: [:show, :edit, :update, :destroy]

  # GET /bank_accounts
  # GET /bank_accounts.json
  def index
    @bank_accounts = BankAccount.all
  end

  # GET /bank_accounts/1
  # GET /bank_accounts/1.json
  def show
  end

  # GET /bank_accounts/new
  def new
    @bank_account = BankAccount.new
  end

  # GET /bank_accounts/1/edit
  def edit
  end

  # POST /bank_accounts
  # POST /bank_accounts.json
  def create
    @bank_account = BankAccount.new(bank_account_params)

    respond_to do |format|
      if @bank_account.save
        format.html { redirect_to @bank_account, notice: 'Bank account was successfully created.' }
        format.json { render :show, status: :created, location: @bank_account }
      else
        format.html { render :new }
        format.json { render json: @bank_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bank_accounts/1
  # PATCH/PUT /bank_accounts/1.json
  def update
    respond_to do |format|
      if @bank_account.update(bank_account_params)
        format.html { redirect_to @bank_account, notice: 'Bank account was successfully updated.' }
        format.json { render :show, status: :ok, location: @bank_account }
      else
        format.html { render :edit }
        format.json { render json: @bank_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bank_accounts/1
  # DELETE /bank_accounts/1.json
  def destroy
    @bank_account.destroy
    respond_to do |format|
      format.html { redirect_to bank_accounts_url, notice: 'Bank account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank_account
      @bank_account = BankAccount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bank_account_params
      params.require(:bank_account).permit(:number, :data_type, :bank_cd, :store_cd, :account_type, :account_number, :account_holder, :account_holder_k, :transfer_method, :transfer_request_date, :stop_flg, :start_date, :end_date)
    end
end

app/helpers/bank_accounts_helper.rb
module BankAccountsHelper
end

app/views/bank_accounts/_form.html.erb
<%= form_for @bank_account, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :number, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :number, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :data_type, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :data_type, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :bank_cd, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :bank_cd, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :store_cd, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :store_cd, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :account_type, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :account_type, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :account_number, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :account_number, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :account_holder, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :account_holder, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :account_holder_k, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :account_holder_k, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :transfer_method, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :transfer_method, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :transfer_request_date, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :transfer_request_date, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :stop_flg, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :stop_flg, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :start_date, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :start_date, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :end_date, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :end_date, :class => 'text_field' %>
    </div>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to 'Cancel', :back, :class => 'btn btn-default'  %>
  <%#= link_to t('.cancel', :default => t("helpers.links.cancel")),
            bank_accounts_path, :class => 'btn btn-default' %>

<% end %>

app/views/bank_accounts/_index.html.erb
<%- model_class = BankAccount -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:data_type) %></th>
      <th><%= model_class.human_attribute_name(:bank_cd) %></th>
      <th><%= model_class.human_attribute_name(:store_cd) %></th>
      <th><%= model_class.human_attribute_name(:account_type) %></th>
      <th><%= model_class.human_attribute_name(:account_number) %></th>
      <th><%= model_class.human_attribute_name(:account_holder) %></th>
      <th><%= model_class.human_attribute_name(:account_holder_k) %></th>
      <th><%= model_class.human_attribute_name(:transfer_method) %></th>
      <th><%= model_class.human_attribute_name(:transfer_request_date) %></th>
      <th><%= model_class.human_attribute_name(:stop_flg) %></th>
      <th><%= model_class.human_attribute_name(:start_date) %></th>
      <th><%= model_class.human_attribute_name(:end_date) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% bank_accounts.each do |bank_account| %>
      <tr>
        <td><%= link_to bank_account.id, bank_account_path(bank_account) %></td>
        <td><%= bank_account.data_type %></td>
        <td><%= bank_account.bank_cd %></td>
        <td><%= bank_account.store_cd %></td>
        <td><%= bank_account.account_type %></td>
        <td><%= bank_account.account_number %></td>
        <td><%= bank_account.account_holder %></td>
        <td><%= bank_account.account_holder_k %></td>
        <td><%= bank_account.transfer_method %></td>
        <td><%= bank_account.transfer_request_date %></td>
        <td><%= bank_account.stop_flg %></td>
        <td><%= bank_account.start_date %></td>
        <td><%= bank_account.end_date %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_bank_account_path(bank_account), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      bank_account_path(bank_account),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_bank_account_path,
            :class => 'btn btn-primary' %>

app/views/bank_accounts/edit.html.erb
<%- model_class = BankAccount -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bank_accounts/index.html.erb
<%- model_class = BankAccount -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:number) %></th>
      <th><%= model_class.human_attribute_name(:data_type) %></th>
      <th><%= model_class.human_attribute_name(:bank_cd) %></th>
      <th><%= model_class.human_attribute_name(:store_cd) %></th>
      <th><%= model_class.human_attribute_name(:account_type) %></th>
      <th><%= model_class.human_attribute_name(:account_number) %></th>
      <th><%= model_class.human_attribute_name(:account_holder) %></th>
      <th><%= model_class.human_attribute_name(:account_holder_k) %></th>
      <th><%= model_class.human_attribute_name(:transfer_method) %></th>
      <th><%= model_class.human_attribute_name(:transfer_request_date) %></th>
      <th><%= model_class.human_attribute_name(:stop_flg) %></th>
      <th><%= model_class.human_attribute_name(:start_date) %></th>
      <th><%= model_class.human_attribute_name(:end_date) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @bank_accounts.each do |bank_account| %>
      <tr>
        <td><%= link_to bank_account.id, bank_account_path(bank_account) %></td>
        <td><%= bank_account.number %></td>
        <td><%= bank_account.data_type %></td>
        <td><%= bank_account.bank_cd %></td>
        <td><%= bank_account.store_cd %></td>
        <td><%= bank_account.account_type %></td>
        <td><%= bank_account.account_number %></td>
        <td><%= bank_account.account_holder %></td>
        <td><%= bank_account.account_holder_k %></td>
        <td><%= bank_account.transfer_method %></td>
        <td><%= bank_account.transfer_request_date %></td>
        <td><%= bank_account.stop_flg %></td>
        <td><%= bank_account.start_date %></td>
        <td><%= bank_account.end_date %></td>
        <td><%=l bank_account.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_bank_account_path(bank_account), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      bank_account_path(bank_account),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_bank_account_path,
            :class => 'btn btn-primary' %>

app/views/bank_accounts/new.html.erb
<%- model_class = BankAccount -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bank_accounts/show.html.erb
<%- model_class = BankAccount -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:number) %>:</strong></dt>
  <dd><%= @bank_account.number %></dd>
  <dt><strong><%= model_class.human_attribute_name(:data_type) %>:</strong></dt>
  <dd><%= @bank_account.data_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:bank_cd) %>:</strong></dt>
  <dd><%= @bank_account.bank_cd %></dd>
  <dt><strong><%= model_class.human_attribute_name(:store_cd) %>:</strong></dt>
  <dd><%= @bank_account.store_cd %></dd>
  <dt><strong><%= model_class.human_attribute_name(:account_type) %>:</strong></dt>
  <dd><%= @bank_account.account_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:account_number) %>:</strong></dt>
  <dd><%= @bank_account.account_number %></dd>
  <dt><strong><%= model_class.human_attribute_name(:account_holder) %>:</strong></dt>
  <dd><%= @bank_account.account_holder %></dd>
  <dt><strong><%= model_class.human_attribute_name(:account_holder_k) %>:</strong></dt>
  <dd><%= @bank_account.account_holder_k %></dd>
  <dt><strong><%= model_class.human_attribute_name(:transfer_method) %>:</strong></dt>
  <dd><%= @bank_account.transfer_method %></dd>
  <dt><strong><%= model_class.human_attribute_name(:transfer_request_date) %>:</strong></dt>
  <dd><%= @bank_account.transfer_request_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:stop_flg) %>:</strong></dt>
  <dd><%= @bank_account.stop_flg %></dd>
  <dt><strong><%= model_class.human_attribute_name(:start_date) %>:</strong></dt>
  <dd><%= @bank_account.start_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:end_date) %>:</strong></dt>
  <dd><%= @bank_account.end_date %></dd>
</dl>

<%= link_to 'Back', :back, :class => 'btn btn-default'  %>
<%#= link_to t('.back', :default => t("helpers.links.back")),
              bank_accounts_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_bank_account_path(@bank_account), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              bank_account_path(@bank_account),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>