config/routes.rb
Rails.application.routes.draw do
  resources :bg_kazeis

  resources :bg_kihon_histories

  resources :bg_kihons

  resources :bank_accounts

  resources :contacts

  resources :addressees

  resources :memos

  root to: 'home#index'
  resources :person_histories

  resources :people do
    resources :person_histories
    resources :memos
    resources :addressees
    resources :contacts
    resources :bank_accounts
  end

end

app/models/memo.rb
class Memo < ActiveRecord::Base
  belongs_to :person, foreign_key: "number", primary_key: "number"
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :set_memo, only: [:show, :edit, :update, :destroy]
  before_action :set_person, only: [:show, :new, :edit, :create, :update, :destroy]

  # GET /memos
  # GET /memos.json
  def index
    @memos = Memo.all
  end

  # GET /memos/1
  # GET /memos/1.json
  def show
  end

  # GET /memos/new
  def new
    #@person = Person.find(params[:person_id])
    @memo = Memo.new(number: @person.number)
  end

  # GET /memos/1/edit
  def edit
  end

  # POST /memos
  # POST /memos.json
  def create
    #@person = Person.find(params[:person_id])
    @memo = Memo.new(memo_params)

    respond_to do |format|
      if @memo.save
        format.html { redirect_to [@person,@memo], notice: 'Memo was successfully created.' }
        format.json { render :show, status: :created, location: @memo }
      else
        format.html { render :new }
        format.json { render json: @memo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memos/1
  # PATCH/PUT /memos/1.json
  def update
    respond_to do |format|
      if @memo.update(memo_params)
        format.html { redirect_to [@person,@memo], notice: 'Memo was successfully updated.' }
        format.json { render :show, status: :ok, location: @memo }
      else
        format.html { render :edit }
        format.json { render json: @memo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memos/1
  # DELETE /memos/1.json
  def destroy
    @memo.destroy
    puts "destroy ----------> "
    respond_to do |format|
      format.html { redirect_to person_url(params[:person_id]), notice: 'Memo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_memo
      #@person = Person.find(params[:person_id])
      @memo = Memo.find(params[:id])
    end
    def set_person
      @person = Person.find(params[:person_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def memo_params
      params.require(:memo).permit(:number, :title, :content)
    end
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/views/memos/_form.html.erb
<%= form_for [@person,@memo], :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :number, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :number, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :content, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :content, :class => 'text_field' %>
    </div>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%#= link_to 'Cancel', :back, :class => 'btn btn-default'  %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            person_path(@person), :class => 'btn btn-default' %>

<% end %>

app/views/memos/_index.html.erb
<%- model_class = Memo -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:content) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% memos.each do |memo| %>
      <tr>
        <td><%= link_to memo.id, person_memo_path(@person,memo) %></td>
        <td><%= memo.title %></td>
        <td><%= memo.content %></td>
        <td><%=l memo.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_person_memo_path(@person,memo), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      person_memo_path(@person,memo),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_person_memo_path(@person),
            :class => 'btn btn-primary' %>

app/views/memos/edit.html.erb
<%- model_class = Memo -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/memos/index.html.erb
<%- model_class = Memo -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:number) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:content) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @memos.each do |memo| %>
      <tr>
        <td><%= link_to memo.id, memo_path(memo) %></td>
        <td><%= memo.number %></td>
        <td><%= memo.title %></td>
        <td><%= memo.content %></td>
        <td><%=l memo.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_memo_path(memo), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      memo_path(memo),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_memo_path,
            :class => 'btn btn-primary' %>

app/views/memos/new.html.erb
<%- model_class = Memo -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/memos/show.html.erb
<%- model_class = Memo -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:number) %>:</strong></dt>
  <dd><%= @memo.number %></dd>
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @memo.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:content) %>:</strong></dt>
  <dd><%= @memo.content %></dd>
</dl>

<%#= link_to 'Back', :back, :class => 'btn btn-default'  %>
<%= link_to t('.back', :default => t("helpers.links.back")),
              person_path(@person), :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_person_memo_path(@person,@memo), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              person_memo_path(@person,@memo),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>